<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Using Include="EPiServer"/>
    <Using Include="EPiServer.Core"/>
    <Using Include="EPiServer.DataAbstraction"/>
    <Using Include="EPiServer.DataAnnotations"/>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="EPiServer.CMS" Version="12.29.0" />
    <PackageReference Include="EPiServer.Find.Cms" Version="16.7.0" />
  </ItemGroup>
  
  <ItemGroup>
    <EmbeddedResource Include="Resources\Translations\**\*" />
  </ItemGroup>

  <ItemGroup>
    <Content Update="SeedData\blog-content.json" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Remove="tmp\blog-facet-multisearch-build\TrainingTest.staticwebassets.runtime.json" />
    <Content Remove="tmp\blog-facet-multisearch-build\TrainingTest.staticwebassets.endpoints.json" />
    <Content Remove="tmp\blog-facet-multisearch-build\TrainingTest.deps.json" />
  </ItemGroup>
  
  <ItemGroup>
    <Folder Include="Models\Media\" />
    <Folder Include="tmp\blog-facet-multisearch-build\cs\" />
    <Folder Include="tmp\blog-facet-multisearch-build\de\" />
    <Folder Include="tmp\blog-facet-multisearch-build\fr\" />
    <Folder Include="tmp\blog-facet-multisearch-build\ko\" />
    <Folder Include="tmp\blog-facet-multisearch-build\pl\" />
    <Folder Include="tmp\blog-facet-multisearch-build\pt-BR\" />
    <Folder Include="tmp\blog-facet-multisearch-build\runtimes\win\lib\net6.0\" />
    <Folder Include="tmp\blog-facet-multisearch-build\tr\" />
    <Folder Include="tmp\blog-search-verification\cs\" />
    <Folder Include="tmp\blog-search-verification\de\" />
    <Folder Include="tmp\blog-search-verification\es\" />
    <Folder Include="tmp\blog-search-verification\it\" />
    <Folder Include="tmp\blog-search-verification\ja\" />
    <Folder Include="tmp\blog-search-verification\ko\" />
    <Folder Include="tmp\blog-search-verification\pl\" />
    <Folder Include="tmp\blog-search-verification\pt-BR\" />
    <Folder Include="tmp\blog-search-verification\runtimes\unix\lib\net6.0\" />
    <Folder Include="tmp\blog-search-verification\runtimes\win-arm64\native\" />
    <Folder Include="tmp\blog-search-verification\runtimes\win-arm\native\" />
    <Folder Include="tmp\blog-search-verification\runtimes\win-x64\native\" />
    <Folder Include="tmp\blog-search-verification\runtimes\win-x86\native\" />
    <Folder Include="tmp\blog-search-verification\runtimes\win\lib\net6.0\" />
    <Folder Include="tmp\blog-search-verification\tr\" />
    <Folder Include="tmp\blog-search-verification\zh-Hans\" />
    <Folder Include="tmp\blog-search-verification\zh-Hant\" />
  </ItemGroup>
  
  <ItemGroup>
    <None Remove="tmp\blog-facet-multisearch-build\pl\Microsoft.CodeAnalysis.resources.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\ja\Microsoft.CodeAnalysis.resources.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\it\Microsoft.CodeAnalysis.resources.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\fr\Microsoft.CodeAnalysis.resources.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\es\Microsoft.CodeAnalysis.resources.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\cs\Microsoft.CodeAnalysis.resources.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\WeCantSpell.Hunspell.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\TrainingTest.exe" />
    <None Remove="tmp\blog-facet-multisearch-build\TrainingTest.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\System.Windows.Extensions.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\System.Configuration.ConfigurationManager.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\SixLabors.ImageSharp.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Newtonsoft.Json.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Newtonsoft.Json.Bson.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.Win32.SystemEvents.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.SqlServer.Server.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.IdentityModel.Tokens.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.IdentityModel.Protocols.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.IdentityModel.Logging.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.IdentityModel.JsonWebTokens.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.IdentityModel.Abstractions.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.Extensions.DependencyModel.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.EntityFrameworkCore.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.Data.SqlClient.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.CodeAnalysis.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.Bcl.AsyncInterfaces.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.AspNetCore.Razor.Language.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.AspNetCore.Mvc.Razor.Extensions.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.AspNetCore.Mvc.NewtonsoftJson.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.AspNetCore.JsonPatch.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Microsoft.AspNetCore.Identity.EntityFrameworkCore.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\MailKit.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.UI.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Shell.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Shell.UI.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.LinkAnalyzer.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Licensing.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Hosting.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Framework.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Find.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Find.UI.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Find.Statistics.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Find.Optimizations.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Find.Framework.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Find.Cms.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Events.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Enterprise.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Data.Cache.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.UI.VisitorGroups.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.UI.Settings.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.UI.AspNetIdentity.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.TinyMce.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.TinyMce.SpellChecker.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.Shell.UI.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.AspNetCore.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.AspNetCore.Templating.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.AspNetCore.Mvc.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.Cms.AspNetCore.HtmlHelpers.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.CMS.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\EPiServer.ApplicationModules.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Castle.Windsor.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Castle.Core.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\BouncyCastle.Crypto.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Azure.Identity.dll" />
    <None Remove="tmp\blog-facet-multisearch-build\Azure.Core.dll" />
  </ItemGroup>
</Project>
